### ISSUE TITLE
Debugging and Testing in NetBeans

### ISSUE THREAD

**Issue by davidsummers** [hneemann/digitalCustomComponents#1]
I discovered your great dynamically loaded digitalCustomComponents java component and was able to use latest maven version to compile it.

It took a while but I finally figured out that in Digital if you set the  Edit -> Settings -> (Attribute Dialog) Java Library field to point to the pluginExample-1.0-SNAPSHOT.jar then the component can be loaded and used in the Digital application.

So far, so good.

I would like to try to *debug* the component in the digitalCustomComponents repository, if possible.

I'm using NetBeans 8.2.

I can:
1. Run -> Build Project
2. Run -> Clean and Build Project
3. Run -> Test Project
4. Debug -> Test File

But when I try:
Debug Main project

It asks for the class to debug and only gives me a choice of
de.neemann.digital.plugin.DemoComponentSource

but then it tried to debug it and says:

--- exec-maven-plugin:1.2.1:exec (default-cli) @ pluginExample ---
Error: Could not find or load main class de.neemann.digital.plugin.DemoComponentSource

Note: I *was* able to debug the test file but I was *not* able to step into the MyAnd or MyOr components to debug them.

Question 1: I noticed that the default profile was for release.  Maybe if I can set that to debug then I can step into the MyOr and/or MyAnd classes?

Question 2: Is there a better way to debug the component, either with Debug -> Main Project or Debug -> Test File?

I'm not very experienced with Java or with NetBeans, just enough to be dangerous.

Thanks for any advise to be able to accomplish this.

**Comment by davidsummers** [comment]
Suggestion: So I was able to figure out how to use the dynamic loaded component in Digital, but it took me a while to figure it out.  Maybe if that process could be documented in the manual it would help others in the future.

**Comment by hneemann** [comment]
I'm not familiar with NetBeans so I can not give advice. I'm an IntelliJ fanboy. ;-)
However, in the DemoComponentSource class, you will find a main method. This method is intended to be used to debug your components. When you start this method, the simulator starts with your components attached to it. And you can also start this method in "debug" mode, and then you can set breakpoints in your code. 
But it's important to remove the jar from the Digital settings, to avoid to attach the components twice!
