### ISSUE TITLE
Test Failure trying to add my own component

### ISSUE THREAD

**Issue by davidsummers** [hneemann/digitalCustomComponents#2]
I'm trying to add my own component.

I've been able to build this component and add the automated test for it in the 'Digital' project.

Everything works when I compile it into the 'Digital' project.

Now I would like to make it a separate dynamically-loaded component that I add in to 'Digital' at run-time instead of compiling it in.

I moved the code (both the component and the component test code) over from my 'Digital' working copy to the digitalCustomComponents working copy and took out the MyAnd, MyOr, etc. and put in my new component.

It all *compiles* but when I try to build, it gets a run-time error of 'java.lang.ExceptionInInitializerError'.   

It seems to point to the following line at the top of my component test JAVA class:
import de.neemann.digital.TestExecuter;

I'm attaching the entire 'mvn install' build log.

[build.log](https://github.com/hneemann/digitalCustomComponents/files/1670680/build.log)

Is there any other information I could supply that would help figure it out?

I've spent about 6 hours trying to figure it out so far without success.

I know it has something to do with a static initializer error, but I can't figure out how to debug it or get closer to figuring it out.

Can you help me figure out why it is failing the build because of a run-time ExceptionInIntializerError?

Thanks in advance.

**Comment by hneemann** [comment]
The error message points to your code.
Without the code there is not much I can do. 
If you can provide the complete code, I will figure out what the problem is.

**Comment by hneemann** [comment]
If you think about it, it's really easy!  ;-)
The Digital.jar file does not contain any test code. This is because test code is not necessary at runtime, it's only needed at build time. Therefore, also the TestExecuter class is not included in Digital.jar. 
If you move your Belt code to a separate project which uses only Digital.jar in its class path, then the TestExecuter is missing.
You have to include the necessary test code to the Belt project, but exclude it from the generated jar file. The easiest way to solve this, is to copy the TestExecuter next to your test case to the belt project.

**Comment by davidsummers** [comment]
After reading what you just said I compared my test code with the MyComponentsTest.java that you had in the original pluginExample and just realized that the MyComponentsTest.java doesn't use the TestExecuter like other test code in the 'Digital' project does, so that probably explains it and why it was confusing me.  I had assumed I could use any class from 'Digital.jar'.

OK, I will try that and report back. 

Thanks.

**Comment by hneemann** [comment]
You can use any class from 'Digital.jar'.
But TestExecuter.class is not part of 'Digital.jar'. That's the problem.
The TestExecuter is part of Digitals test sources, but it's not packaged into 'Digital.jar'.

**Comment by shawty** [comment]
I had a similar problem, so I stripped EVERYTHING out of the component except for MyAnd and the ComponentSource class.

I'm using netbeans, so I just simply created a new JavaSE class project, dropped the componentsource class and the myand class into it, then I right clicked on my project in Netbeans, went to project properties and set the main class as the componentsource class.

Once you do this, when you do a clean build, you can then just point to the jar file in digital's settings and all should be good.

I've just finished porting my RTC component over from Logisim and it works great.
